# 多环境配置 dev、stage、prod 。链接：https://blog.51cto.com/u_15078285/2759591
spring.profiles.active=dev

#
#
# 配置 log
# 输出的地址和输出级别
logging.file.name=./ByYourSide/config/logs/side.log
logging.level.com.favorites=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.hibernate=ERROR
#
#
# 格式化时间，全局配置
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=GMT+8