export const COMMON_ERROR_CODES = {
  INTERNAL_SERVER_ERROR: 10000,
  VALIDATION_ERROR: 10001,
  UNAUTHORIZED: 10002,
  FORBIDDEN: 10003,
  NOT_FOUND: 10004,
} as const;

export type CommonErrorCode =
  (typeof COMMON_ERROR_CODES)[keyof typeof COMMON_ERROR_CODES];
